### ISSUE TITLE
Add TS.RANGE command complexity description

### ISSUE THREAD

**Issue by r-alekseev** [danni-m/redis-timeseries#11]
Hello danni-m! Please tell about the time complexity of TS.RANGE in the README.md.

**Comment by danni-m** [comment]
Hi,
TS.RANGE complexity is O(n/m+k*m)
n = number of data points
m = chunk size (data points per chunk)
k = number of data points that are in the requested range

This can be improved in the future by using binary search to find the start of the range, which will make this O(Log(n/m)+k*m), but since m is pretty small, we can neglect it at look at the operation as O(Log(n) + k). 
@r-alekseev i hope this answers your question, i'll document it better.
Thanks for the feedback!

**Comment by r-alekseev** [comment]
Thank you, @danni-m!
